swagger: "2.0"
info:
  description: "Hello World."
  version: "1.0.0"
  title: "Hello World for Ktor"
  termsOfService: "https://kght6123.page/privacy-policy/"
  contact:
    email: "admin@kght6123.work"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
- name: "hello"
  description: "hello api."
  externalDocs:
    description: "My Blog."
    url: "https://kght6123.page"
schemes:
- "https"
- "http"
paths:
  /hello:
    post:
      tags:
      - "hello"
      summary: "Add a new hello to the store"
      description: ""
      operationId: "addHello"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "hello object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Hello"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  Hello:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      name:
        type: "string"
        example: "world"
      tags:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
      status:
        type: "string"
        description: "hello status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
    xml:
      name: "Hello"

